version: 2

project_name: loggerrific

# Pre-release hooks
before:
  hooks:
    - go mod tidy

# Skip building binaries since this is a library
builds:
  - skip: true

# Create GitHub release
release:
  github:
    owner: CallumKerson
    name: loggerrific
  name_template: "{{.Tag}}"
  draft: false
  prerelease: auto
  mode: replace

# Generate changelog from git commits
changelog:
  use: github
  sort: asc
  abbrev: 0
  groups:
    - title: "🚀 New Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 100
    - title: "🔒 Security Updates"
      regexp: '^.*?sec(\([[:word:]]+\))??!?:.+$'
      order: 150
    - title: "🐛 Bug Fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 200
    - title: "⚡ Performance Improvements"
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 300
    - title: "♻️ Refactors"
      regexp: '^.*?refactor(\([[:word:]]+\))??!?:.+$'
      order: 400
    - title: "🧪 Tests"
      regexp: '^.*?test(\([[:word:]]+\))??!?:.+$'
      order: 500
    - title: "📚 Documentation Updates"
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 600
    - title: "🔧 Build System"
      regexp: '^.*?(build|ci)(\([[:word:]]+\))??!?:.+$'
      order: 700
    - title: "📦 Other Changes"
      order: 999
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "typo"
      - "^chore"

# Create simple archive with docs
archives:
  - files:
      - README.md
      - LICENSE
      - "*.go"
      - "**/*.go"
